version: '3.0'

expectations:
  population_size: 1000

actions:

  generate_cohorts_main:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_ori
    outputs:
      highly_sensitive:
        cohort: output/input_ori.csv

  run_model:
    run: r:latest analysis/01-createSDtables.R
    needs: [generate_cohorts_main]
    outputs:
      moderately_sensitive:
        log: logs/log-01-createSDtables.txt
        rdata1: outputs/gt_ocpop.RData
        rdata2: outputs/gt_gpcpop.RData
        tb01: outputs/tb01_gpcr_region.csv
        tb02: outputs/tb02_gpcr_stp.csv
        tb04: outputs/tb04_gpcr_agesex.csv
        tb05: outputs/tb05_gpcr_ethnicity.csv
        tb06: outputs/tb06_gpcr_ruc.csv
        tb07: outputs/tb07_gpcr_care.csv
        tb08: outputs/tb08_gpcr_dis.csv

  # https://docs.opensafely.org/en/latest/measures/
    generate_cohorts_long:
      run: cohortextractor:latest generate_cohort --study-definition study_definition_measures_bycode --index-date-range "2019-07-01 to 2020-12-01 by month"
      outputs:
        highly_sensitive:
          cohort: output/input_measures_bycode_*.csv

    run_model_long:
      run: r:latest analysis/03-createnattrends_codes.R
      needs: [generate_cohorts_long]
      outputs:
        moderately_sensitive:
          log: logs/log-03-createnattrends.txt
          tb01: output/sc03_tb01_nattrends.csv
          fig01: output/sc03_fig01_nattrends.png
          fig02: output/sc03_fig02_nattrends.png


  run_all:
    needs:
      - run_model
    # In order to be valid this action needs to define a run commmand and some
    # output. We don't really care what these are but the below does the trick.
    # In a future release of the platform, this special action won't need to be
    # defined at all.
    run: cohortextractor:latest --version
    outputs:
      moderately_sensitive:
        whatever: project.yaml
