version: '3.0'

expectations:
  population_size: 1000

actions:

  generate_cohorts_main:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_ori
    outputs:
      highly_sensitive:
        cohort: output/input_ori.csv

  run_model:
    run: r:latest analysis/01-createSDtables.R
    needs: [generate_cohorts_main]
    outputs:
      moderately_sensitive:
        log: logs/log-01-createSDtables.txt
        #gtpng1: output/tables/gt_ocpop.png
        #gtpng2: output/tables/gt_gpcpop.png
        rdata1: output/gt_ocpop.RData
        rdata2: output/gt_gpcpop.RData
        #tb01: output/tb01_gpcr_region.csv
        tb02: output/tb02_gpcr_stp.csv
        tb04: output/tb04_gpcr_agesex.csv
        tb05: output/tb05_gpcr_ethnicity.csv
        tb06: output/tb06_gpcr_ruc.csv
        tb07: output/tb07_gpcr_care.csv
        tb08: output/tb08_gpcr_dis.csv

  # https://docs.opensafely.org/en/latest/measures/
  generate_cohorts_long:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_measures_bycode --index-date-range "2019-01-01 to 2020-12-01 by month" --output-dir=output/measures
    outputs:
      highly_sensitive:
        cohort: output/measures/input_measures_bycode_*.csv

  generate_measures:
    run: cohortextractor:latest generate_measures --study-definition study_definition_measures_bycode --output-dir=output/measures
    needs: [generate_cohorts_long]
    outputs:
      moderately_sensitive:
        measure_csv: output/measures/measure_*.csv

  run_model_long:
    run: r:latest analysis/03-createnattrends_codes.R
    needs: [generate_cohorts_long]
    outputs:
      moderately_sensitive:
        log: logs/log-03-createnattrends.txt
        tb01: output/sc03_tb01_nattrends.csv
        fig01: output/sc03_fig01_nattrends.svg
        fig02: output/sc03_fig02_nattrends.svg

  run_model_measures:
    run: r:latest analysis/02-createtemporal.R
    needs: [generate_cohorts_long,generate_measures]
    outputs:
      moderately_sensitive:
        log: logs/log-02-createtemporal.txt
        tb01: output/measures_gpc_pop.csv
        fig01: output/plots/plot_overall_gpc_pop.svg
        figall: output/plots/plot_each_OC_*_practice.svg
        figquant: output/plots/plot_quantiles_OC_*_practice.svg
